FloatLayout:
    MDTextField:
        hint_text: "name"
        pos_hint: {'center_x': 0.5, 'center_y': 0.8}
        id: textfield
        
    MDRaisedButton:
        pos_hint: {'center_x': 0.5, 'center_y': 0.65}
        text: "Add Athlete"  
        on_press: app.add_athlete()  



    MDRaisedButton:
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        id: dropdownbutton
        text: "Open Menu"
        on_press: app.open_dropdown()    